
services:
  app:
    build:
      context: .
    environment:
      # logger
      LOGGER_CALLER: 0
      LOGGER_STACKTRACE: 1
      LOGGER_LEVEL: debug
      # database
      DB_HOST: mysql:3306
      DB_USER: root
      DB_PASSWORD: root
      DB_BASE: test
      # exchange
      EXCHANGE_URL: wss://ws-feed.exchange.coinbase.com
      EXCHANGE_ORIGIN: https://coinbase.com
      EXCHANGE_PROTOCOL:
      EXCHANGE_SYMBOLS: ETH-USD
      EXCHANGE_CHANNELS: full
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - local
    env_file:
      - env.list

  mysql:
    image: mysql
    environment:
      # MYSQL_USER: test_mysql
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      # Be careful! It's public port only for test. Remove this block if run in production.
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-db:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mysql-db: