### Get the largest orders
GET http://localhost:8090/btc/largest-orders
Content-Type: application/json


### Get the largest received orders
GET http://localhost:8090/btc/largest-received-orders
Content-Type: application/json


### Get the largest open orders
GET http://localhost:8090/btc/largest-open-orders
Content-Type: application/json
