#local IP
@localUrl = http://localhost:8090
@testUrl = http://3.145.37.65:8090

### Get the largest match orders (local)
GET {{localUrl}}/api/v1/btc/largest-match-orders?hours=240&limit=100
Content-Type: application/json

### Get the largest match orders (test)
GET {{testUrl}}/api/v1/btc/largest-match-orders?hours=200&limit=100
Content-Type: application/json


### Get the largest received orders
GET http://localhost:8090/api/v1/btc/largest-received-orders?hours=240&limit=100
Content-Type: application/json


### Get the largest open orders
GET http://localhost:8090/api/v1/btc/largest-open-orders?hours=240&limit=100
Content-Type: application/json

### Store received orders in supabase
POST http://localhost:8090/api/v1/btc/store-received-orders
Content-Type: application/json

{
    "hours": 240,
    "limit": 50
}

### Store match orders in supabase
POST http://localhost:8090/api/v1/btc/store-match-orders
Content-Type: application/json

{
    "hours": 240,
    "limit": 50
}

### Start a task
POST http://localhost:8090/api/v1/btc/scheduler/start
Content-Type: application/json

{
    "schedule": "*/10 * * * * *",
    "hours": 240,
    "limit": 50
}

### Stop a task
DELETE http://localhost:8090/api/v1/btc/scheduler/stop/2
Content-Type: application/json


### List all tasks
GET http://localhost:8090/api/v1/btc/scheduler/tasks
Content-Type: application/json
