### Get the largest orders
GET http://localhost:8090/api/v1/btc/largest-match-orders?hours=24&limit=100
Content-Type: application/json


### Get the largest received orders
GET http://localhost:8090/api/v1/btc/largest-received-orders?hours=240&limit=100
Content-Type: application/json


### Get the largest open orders
GET http://localhost:8090/api/v1/btc/largest-open-orders?hours=240&limit=100
Content-Type: application/json
