name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  tests:
    environment: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - run: go version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download && go mod tidy

      - name: Unit Tests
        run: make test

  goreleaser:
    environment: released
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - run: go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}